version: "3.0"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./frontend/:/app
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - MONGOHOST=cluster0-ipauv.mongodb.net
      - MONGOPORT=27017
      - MONGODATABASE=node-express
      - MONGOUSER=ankit
      - MONGOPASSWORD=6jPLarTpFYLRVLXh
    links:
      - database
  database:
    image: "mongo:latest"
    ports:
      - "27017:27017"
